### ISSUE TITLE
Adding nixGL

### ISSUE THREAD

**Issue by ldesousa** [imincik/my-geospatial-nix-flake#1]
I tried to add nixGL to the flake in [this commit](https://github.com/imincik/my-geospatial-nix-flake/compare/master...ldesousa:my-geospatial-nix-flake:master). This formulation fails with these error messages:

```
error:
       … while updating the lock file of flake 'git+file:///home/lads/git/my-geospatial-nix-flake'

       … while updating the flake input 'nixgl'

       error: cannot find flake 'flake:nixgl' in the flake registries
```

How can I add the nixGL package to this flake?

**Comment by imincik** [comment]
nixGL and some docs added in https://github.com/imincik/my-geospatial-nix-flake/commit/95997afa1139bb5b20d71a8789f81029b959770d
